package com.ssomar.score.usedapi;

import org.bukkit.Location;
import org.bukkit.block.Block;

import java.util.Iterator;
import java.util.UUID;
import java.util.concurrent.ConcurrentLinkedDeque;

/**
 * Tracks blocks that are about to be smelted by an EI/EB command (SMELT, MINEINCUBE smelt, VEINBREAKER smelt, ...)
 * so that the extra drops generated by AuraSkills abilities (LootDropEvent, e.g. cause MINING_LUCK)
 * on the same block can also be smelted.
 * This class must not reference any AuraSkills class, it is also loaded when AuraSkills is not installed.
 */
public class AuraSkillsSmeltTracker {

    /* The LootDropEvent is fired during the BlockBreakEvent generated by the smelt commands,
     * or up to some ticks later for the drops scheduled by AuraSkills */
    private static final long EXPIRATION_MS = 2000;

    private static final ConcurrentLinkedDeque<PendingSmelt> pendingSmelts = new ConcurrentLinkedDeque<>();

    private static class PendingSmelt {
        final UUID playerUUID;
        final String worldName;
        final int x;
        final int y;
        final int z;
        final long time;

        PendingSmelt(UUID playerUUID, Block block) {
            this.playerUUID = playerUUID;
            this.worldName = block.getWorld().getName();
            this.x = block.getX();
            this.y = block.getY();
            this.z = block.getZ();
            this.time = System.currentTimeMillis();
        }
    }

    /* Must be called BEFORE the block is broken, the AuraSkills luck is rolled during the BlockBreakEvent */
    public static void recordSmelt(UUID playerUUID, Block block) {
        if (playerUUID == null || !Dependency.AURA_SKILLS.isInstalled()) return;
        purgeExpired();
        pendingSmelts.add(new PendingSmelt(playerUUID, block));
    }

    public static boolean wasRecentlySmelted(UUID playerUUID, Location dropLocation) {
        if (playerUUID == null || dropLocation == null || dropLocation.getWorld() == null) return false;
        purgeExpired();
        String worldName = dropLocation.getWorld().getName();
        int x = dropLocation.getBlockX();
        int y = dropLocation.getBlockY();
        int z = dropLocation.getBlockZ();
        for (PendingSmelt pending : pendingSmelts) {
            if (pending.playerUUID.equals(playerUUID)
                    && pending.x == x && pending.y == y && pending.z == z
                    && pending.worldName.equals(worldName)) {
                return true;
            }
        }
        return false;
    }

    private static void purgeExpired() {
        long limit = System.currentTimeMillis() - EXPIRATION_MS;
        Iterator<PendingSmelt> it = pendingSmelts.iterator();
        while (it.hasNext()) {
            if (it.next().time < limit) it.remove();
            else break;
        }
    }
}
