package com.ssomar.score.usedapi;

import com.ssomar.score.commands.runnable.block.commands.Smelt;
import dev.aurelium.auraskills.api.event.loot.LootDropEvent;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.inventory.ItemStack;

/**
 * Smelts the extra drops generated by AuraSkills abilities (e.g. Mining Luck / Luck double drops)
 * when the broken block was smelted by an EI/EB command (SMELT, MINEINCUBE smelt, VEINBREAKER smelt, ...)
 * Only registered when AuraSkills is installed, this class references AuraSkills classes.
 */
public class AuraSkillsLootDropListener implements Listener {

    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    public void onLootDrop(LootDropEvent e) {
        ItemStack item = e.getItem();
        if (item == null) return;

        ItemStack smelted = Smelt.getSmeltedItem(item.getType());
        if (smelted == null) return;

        if (!AuraSkillsSmeltTracker.wasRecentlySmelted(e.getPlayer().getUniqueId(), e.getLocation())) return;

        smelted.setAmount(item.getAmount());
        e.setItem(smelted);
    }
}
